### ISSUE TITLE
error new update

### ISSUE THREAD

**Issue by rafaena** [Klaus3d3/xDrip-Watchface#7]
good morning, with the new update of the repair of December failure to stop working and gives error, to changed some way to set it? thank you very much a great job klaus3d3

**Comment by GreatApo** [comment]
The previous version doesn't give you an error?

**Comment by rafaena** [comment]
the previous version only gave me the month of December

**Comment by rafaena** [comment]
with the last update of watchface of 5 days ago I have an error and do not communicate smartwatch and telephone

**Comment by GreatApo** [comment]
I am asking because there was also an update of Stratos that brakes the libraries so I am trying to figure out whether it is watchface's update or watch's update.

Hence, if you now install the previous version, it works without problems? (Let aside the month bug)

**Comment by rafaena** [comment]
![15481951631584472168706396553275](https://user-images.githubusercontent.com/10066930/51569136-d0999100-1e9b-11e9-9470-a3d6c16c89f4.jpg)

**Comment by rafaena** [comment]
![15481955466117199078304218351944](https://user-images.githubusercontent.com/10066930/51569260-2837fc80-1e9c-11e9-8388-0a3cd013f83a.jpg)
![15481955958051902456142625904671](https://user-images.githubusercontent.com/10066930/51569314-47cf2500-1e9c-11e9-89f1-a60d3aeb9f4b.jpg)

**Comment by rafaena** [comment]
![15481961653644563443696748185745](https://user-images.githubusercontent.com/10066930/51569767-9b8e3e00-1e9d-11e9-8d65-c86f9c7ac192.jpg)

yes, I will go back to the previous version to make it work, thank you very much

**Comment by GreatApo** [comment]
Follow these steps:
- Clean your screen 😆 
- Get an error log

To get the log:
Load the watchface, and after it crashes, run the command:
adb logcat >log.txt
You will see the file created, press ctrl+c on the console

**Comment by rafaena** [comment]
nothing, it does not work
![15482712952985328968258458791152](https://user-images.githubusercontent.com/10066930/51631277-8f14ee80-1f4c-11e9-8a8c-6bb45f04ed0f.jpg)

**Comment by Klaus3d3** [comment]
the last log from xdrip seems ok. its always first "unconnected" and the does a retry, wich should give an "OK" like it does in you log.

It does not mean per se that the Watch works, of cause.

could you try to switch the "every minute update" on the widgets setup page?

**Comment by Klaus3d3** [comment]
i did a short test, the every minute update seems broken anyway. ;-)

**Comment by Klaus3d3** [comment]
by the way, there is a new data entry mode in the widget. it works, but is not very safe to use. so leave it until i fixed it.

**Comment by rafaena** [comment]
Thank you for your indications klaus 3d3, I changed the phone thinking about solving it, but it was not fixed,
![img_20190125_153126](https://user-images.githubusercontent.com/10066930/51752338-87be2400-20b7-11e9-8ca5-ccba163a85d7.jpg)

**Comment by Klaus3d3** [comment]
It's not the phone. Xdrips Log shows that its working. Its something strange with your watch.
The graph button is selected, but your on the setup page.
Again switch off " Update WF every minute" - wich seems broken-
and try this:

Change Watchface to something else
reboot
Change it back to xdrip watchface.
tick on "Send data to watch" on your phone. (Maybe twice)

**Comment by yosepito** [comment]
May be it be an absolute nonsense, but just in case: @rafaena, do you have Amazfit app activated and running in your smartphone? Another potential issue in the phone is the battery saver and perhaps the energy configuration killing the service or so.
Normally, changing the watchface and rebooting and then selecting again the xdrip watchface will re-start the service in the watch, which makes sense
Try also to change the language from Spanish to English and from English to Spanish...
@rafaena, I'm Spanish as well, but I own a Pace, not a Stratos, so I cannot replicate the problem. Should you need assistance, please send me a private message

**Comment by rafaena** [comment]
Thanks for your recommendations, but it could not be made to work. I also format the clock and it did not work. I reinstall the previous version and it works perfectly. Thanks for your help
![15484541763012079681579728411868](https://user-images.githubusercontent.com/10066930/51775949-a8a66980-20f7-11e9-8316-02ba01c5d88d.jpg)

**Comment by caiobarreto** [comment]
Hello Guys, any chance we have some style update? I mean have more options for colors, background etc?

**Comment by jbm76** [comment]
> 
> 
> Thanks for your recommendations, but it could not be made to work. I also format the clock and it did not work. I reinstall the previous version and it works perfectly. Thanks for your help
> ![15484541763012079681579728411868](https://user-images.githubusercontent.com/10066930/51775949-a8a66980-20f7-11e9-8316-02ba01c5d88d.jpg)

I'm in the same situation as Andres ... Impossible to work with this new version.
I have exactly the same screenshots that the partner attached, with this last version it does not work for me.
I have returned to the previous version and everything is perfect again.

Thank you all for your work

**Comment by yosepito** [comment]
Sorry: I cannot test it for some weeks because I need it to be fully operative (mine is Pace). I will try it later (I need a couple of weeks). 
Anyway, I realized that there are several changes, the size increased from 2,11 MB to more than 11MB and there is also a major change relative to the SDK language level from 1_7 to 1_8 and some other relative to compiling versions (target SDK version 27 vs 22 and other similar changes). Could this cause any problem when deploying it to the watch due to any incompatibility with current version of watch's software?

I will try the updated version in a couple of weeks, provided I can go back to previous one

**Comment by vebaba** [comment]
I have had same issue. 2018 klaus'es xdrip and old watchface worked but that version made g5 transmitter battery drain. So, I updated Xdrip to the latest nightly and Pace xdrip watchface stopped to work.
What made it work? I reset watch to factory settings and then installed latest klaus'es xdrip watchface and it got connected after 1 'resend glucose to watch' from xdrip

cheers!
